steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/babycare-api',
        '--build-arg', 'GOOGLE_APPLICATION_CREDENTIALS=gcp-key.json',
        '.'
      ]

images:
  - 'gcr.io/$PROJECT_ID/babycare-api'