name: Deploy Backend to Cloud Run

on:
  push:
    paths:
      - 'backend/**'
    branches: [main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: axial-trail-460618-u6

      - name: Write service account key to file
        run: echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json

      - name: Submit build using cloudbuild.yaml
        run: |
          cp gcp-key.json backend/gcp-key.json
          cd backend
          gcloud builds submit . \
            --config=cloudbuild.yaml \
            --gcs-log-dir=gs://axial-trail-460618-u6_cloudbuild/build-logs/

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy babycare-api \
            --image gcr.io/axial-trail-460618-u6/babycare-api \
            --region us-east1 \
            --platform managed \
            --port 8080 \
            --cpu=1 \
            --memory=1Gi \
            --min-instances=0 \
            --max-instances=1 \
            --concurrency=80 \
            --timeout=2400 \
            --ingress=all \
            --service-account=backend-access-all@axial-trail-460618-u6.iam.gserviceaccount.com