name: Deploy Frontend to Cloud Run

on:
  push:
    paths:
      - 'frontend/**'
    branches: [main]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies & build
        run: |
          cd frontend
          npm install

      - name: Inject .env from GitHub Secrets
        run: |
          cat <<EOF > frontend/.env
          VITE_API_URL=${{ secrets.VITE_API_URL }}
          VITE_API_URL_PEDITRICIAN=${{ secrets.VITE_API_URL_PEDITRICIAN }}
          VITE_API_URL_SQL=${{ secrets.VITE_API_URL_SQL }}
          VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_INACTIVITY_TIMEOUT_MS=${{ secrets.VITE_INACTIVITY_TIMEOUT_MS }}
          EOF

      - name: Debug- Print env keys (no values)
        run: |
          echo "Inspecting .env file keys:"
          grep -E '^VITE_' frontend/.env | cut -d '=' -f 1

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Inspect built JS for Firebase API key
        run: |
          grep -r "AIza" frontend/dist || echo "No API key found in built files"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: axial-trail-460618-u6

      - name: Write service account key to file
        run: echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json

      - name: Build and push Docker image
        run: |
          cd frontend
          gcloud builds submit . \
            --tag gcr.io/axial-trail-460618-u6/babycare-frontend-login \
            --gcs-log-dir=gs://axial-trail-460618-u6_cloudbuild/build-logs

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy babycare-frontend \
            --image gcr.io/axial-trail-460618-u6/babycare-frontend-login \
            --region us-east1 \
            --platform managed \
            --port 80 \
            --cpu=1 \
            --memory=1Gi \
            --min-instances=0 \
            --max-instances=1 \
            --concurrency=80 \
            --timeout=2400 \
            --allow-unauthenticated \
            --ingress=internal-and-cloud-load-balancing \
            --service-account=frontendaccess-babyapp@axial-trail-460618-u6.iam.gserviceaccount.com

      - name: Clean up secrets file
        run: rm gcp-key.json